spring:
  datasource:
    url: jdbc:h2:mem:codeflix_catalog_db;MODE=MYSQL;DATABASE_TO_LOWER=TRUE
    username: test
    password: test
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
