CREATE TABLE CATEGORY (
    ID VARCHAR(36) NOT NULL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(4000),
    ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    CREATED_AT DATETIME(6) NOT NULL,
    UPDATED_AT DATETIME(6) NOT NULL,
    DELETED_AT DATETIME(6) NULL
);